first_value = int(input("Enter 1. value: "))
typeoffirst_value = type(first_value) 
print("The type of the first value is {}".format(typeoffirst_value))
second_value = str(input("Enter 2. value: "))
typeofsecond_value = type(second_value) 
print("The type of the second value is {}".format(typeofsecond_value))
thirth_value = int(input("Enter 3. value: "))
typeofthirth_value = type(thirth_value) 
print("The type of the thirth value is {}".format(typeofthirth_value))
fourth_value = float(input("Enter 4. value: "))
typeoffourth_value = type(fourth_value) 
print("The type of the fourth value is {}".format(typeoffourth_value))
fifth_value = str(input("Enter 5. value: "))
typeoffifth_value = type(fifth_value) 
print("The type of the fifth value is {}".format(typeoffifth_value))